export enum ConfigNames {
  APP = 'CONFIG_APP',
  API = 'CONFIG_API',
  AUTH = 'CONFIG_AUTH',
  TELEGRAM = 'CONFIG_TELEGRAM',
  USERS = 'CONFIG_USERS',
  GOOGLE_SHEETS = 'CONFIG_GOOGLE_SHEETS',
  DATABASE = 'CONFIG_DATABASE',
}
